### ISSUE TITLE
custom CACHE_ROOT

### ISSUE THREAD

**Issue by leoatchina** [daquexian/tagls#1]
My gtags files is stored in  `~/.LfCache/gtags`,  so there is a need to customize `CACHE_ROOT`

**Comment by daquexian** [comment]
Thanks for your issue!

Leaderf manages the generation/update of gtags files itself, which may interfere with tagls. Do you want tagls in a "readonly" mode if leaderf presents?

**Comment by leoatchina** [comment]
Yes, I think it is a good solution.

**Comment by daquexian** [comment]
It's supported in v0.0.3 :)
